# Generated by Django 3.2.8 on 2021-10-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211012_0013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Cliente',
        ),
    ]
